apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: id2vd70pf-nodejs-gitops
  description: This is GitOps manifest for id2vd70pf-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: id2vd70pf-nodejs
    janus-idp.io/tekton: id2vd70pf-nodejs
    backstage.io/kubernetes-id: id2vd70pf-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:id2vd70pf-nodejs
