apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: id2vd70pf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: id2vd70pf-nodejs 
  name: id2vd70pf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: id2vd70pf-nodejs 
